//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultural_eventlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cultural_eventlist()
        {
            this.Cultural_reg = new HashSet<Cultural_reg>();
        }
    
        public int cul_evid { get; set; }
        public string event_name { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public Nullable<System.TimeSpan> event_time { get; set; }
        public string event_venue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cultural_reg> Cultural_reg { get; set; }
    }
}
